import type { Metadata } from "next";
import { ThemeModeScript } from "flowbite-react";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({ subsets: ["cyrillic"], weight: "400" });

export const metadata: Metadata = {
  title: "Генерация пин-кодов для авторизации — pin-codes.ru",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <head>
        <ThemeModeScript />
      </head>
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
