import type { Metadata } from "next";
import { ThemeModeScript } from "flowbite-react";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({ subsets: ["cyrillic"], weight: "400" });

export const metadata: Metadata = {
  title: "Генерация пин-кодов для авторизации — pin-codes.ru",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <head>
        <ThemeModeScript />
        <script
          dangerouslySetInnerHTML={{
            __html: `
(function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
m[i].l=1*new Date();
for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
(window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

ym(96492391, "init", {
    clickmap:true,
    trackLinks:true,
    accurateTrackBounce:true
});`,
          }}
        />
      </head>
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
